"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { Menu, X } from "lucide-react";
import { cn } from "@/lib/utils/cn";
import { SymbolSearch } from "./symbol-search";

const NAV = [
  { href: "/dashboard", label: "Dashboard" },
  { href: "/screener", label: "Screener" },
  { href: "/backtest", label: "Backtest" },
];

export function AppNav() {
  const pathname = usePathname();
  const [mobileOpen, setMobileOpen] = useState(false);

  return (
    <header className="sticky top-0 z-40 border-b border-[color-mix(in_oklab,var(--color-ink-600)_45%,transparent)] bg-[color-mix(in_oklab,var(--color-ink-900)_88%,transparent)] backdrop-blur-xl">
      <div className="mx-auto flex h-16 max-w-[1400px] items-center gap-4 px-4 sm:px-6">
        <Link href="/" className="flex shrink-0 items-center gap-2.5" aria-label="MarketMind home">
          <Logo />
          <span className="font-display text-lg tracking-tight">MarketMind</span>
        </Link>

        <nav className="hidden items-center gap-1 md:flex" aria-label="Main">
          {NAV.map((item) => {
            const isActive = pathname === item.href || pathname.startsWith(`${item.href}/`);
            return (
              <Link
                key={item.href}
                href={item.href}
                className={cn(
                  "rounded-full px-3.5 py-1.5 text-sm transition-colors",
                  isActive
                    ? "bg-[var(--color-ink-700)] text-[var(--color-paper)]"
                    : "text-[var(--color-paper-dim)] hover:text-[var(--color-paper)]",
                )}
              >
                {item.label}
              </Link>
            );
          })}
        </nav>

        <div className="ml-auto hidden w-full max-w-md lg:block">
          <SymbolSearch />
        </div>

        <button
          type="button"
          onClick={() => setMobileOpen((v) => !v)}
          className="ml-auto grid size-9 place-items-center rounded-lg border border-[var(--color-ink-600)] text-[var(--color-paper-dim)] md:hidden"
          aria-label={mobileOpen ? "Close menu" : "Open menu"}
          aria-expanded={mobileOpen}
        >
          {mobileOpen ? <X size={18} /> : <Menu size={18} />}
        </button>
      </div>

      {mobileOpen && (
        <div className="border-t border-[var(--color-ink-700)] px-4 py-4 md:hidden">
          <SymbolSearch />
          <nav className="mt-3 flex flex-col gap-1" aria-label="Mobile">
            {NAV.map((item) => (
              <Link
                key={item.href}
                href={item.href}
                onClick={() => setMobileOpen(false)}
                className="rounded-lg px-3 py-2 text-sm text-[var(--color-paper-dim)] hover:bg-[var(--color-ink-800)] hover:text-[var(--color-paper)]"
              >
                {item.label}
              </Link>
            ))}
          </nav>
        </div>
      )}

      <div className="px-4 pb-3 lg:hidden sm:px-6">
        <div className="hidden md:block">
          <SymbolSearch />
        </div>
      </div>
    </header>
  );
}

export function Logo({ size = 26 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 32 32" fill="none" aria-hidden="true">
      <rect width="32" height="32" rx="8" fill="var(--color-ink-700)" />
      {/* A rising structure of higher lows — the product's core idea in a mark. */}
      <path
        d="M7 22.5L12 17.5L16.5 21L25 10"
        stroke="var(--color-signal-500)"
        strokeWidth="2.2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle cx="25" cy="10" r="2.6" fill="var(--color-signal-500)" />
    </svg>
  );
}

export function AppFooter() {
  return (
    <footer className="mt-16 border-t border-[color-mix(in_oklab,var(--color-ink-600)_40%,transparent)]">
      <div className="mx-auto max-w-[1400px] px-4 py-8 sm:px-6">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-2.5">
            <Logo size={20} />
            <span className="text-sm text-[var(--color-paper-dim)]">
              MarketMind — swing and positional analysis
            </span>
          </div>
          <nav className="flex gap-4 text-sm text-[var(--color-paper-faint)]" aria-label="Footer">
            <Link href="/dashboard" className="hover:text-[var(--color-paper)]">Dashboard</Link>
            <Link href="/screener" className="hover:text-[var(--color-paper)]">Screener</Link>
            <Link href="/backtest" className="hover:text-[var(--color-paper)]">Backtest</Link>
          </nav>
        </div>
        <p className="mt-6 max-w-3xl text-xs leading-relaxed text-[var(--color-paper-faint)]">
          Analysis is generated by a rules engine from historical price and filing data. It is not investment advice and
          does not account for your circumstances. Market data may be delayed or, where a live source is unavailable,
          replaced by clearly labelled sample data. Do your own research before acting.
        </p>
      </div>
    </footer>
  );
}
